// frontend-react/src/App.tsx
import { StrictMode } from 'react';
import urlJoin from 'url-join';

import { useFetchData } from './hooks';
import { TodosResponse } from '../schema';
import { Filters, TodoList } from './components';

export const App = () => {
  const { data, isLoading, error } = useFetchData<TodosResponse>(
    urlJoin(import.meta.env.VITE_API_URL, '/api/todos'),
  );

  return (
    <StrictMode>
      <section className="todoapp">
        <header className="header">
          <h1>todos</h1>
          <input className="new-todo" placeholder="What needs to be done?" autoFocus />
        </header>
        <section className="main">
          <input id="toggle-all" className="toggle-all" type="checkbox" />
          <label htmlFor="toggle-all">Mark all as complete</label>
          {!isLoading && !error && <TodoList todos={data.data!} />}
        </section>
        <footer className="footer">
          <span className="todo-count">
            <strong>{data?.data?.filter((todo) => !todo.completed).length ?? 0}</strong> items left
          </span>
          <Filters />
          <button className="clear-completed">Clear completed</button>
        </footer>
      </section>
      <footer className="info">
        <p>Double-click to edit a todo</p>
      </footer>
    </StrictMode>
  );
};

// frontend-vue/src/App.vue
<script setup lang="ts">
import NewTodo from './components/NewTodo.vue';
import TodoList from './components/TodoList.vue';
import Filters from './components/Filters.vue';

import { ref } from 'vue';
import type { Todo } from './schema';

const count = ref(0);

function increment() {
  count.value++;
}

const todos: Todo[] = [
  { id: '1', title: 'My journey with Vue', completed: false },
  { id: '2', title: 'Blogging with Vue', completed: false },
  { id: '3', title: 'Why Vue is so fun', completed: false },
];
</script>

<template>
  <section class="todoapp">
    <header class="header">
      <h1>todos</h1>
      <NewTodo />
    </header>
    <section class="main">
      <input id="toggle-all" class="toggle-all" type="checkbox" />
      <label for="toggle-all">Mark all as complete</label>
      <TodoList :todos="todos" />
    </section>
    <footer class="footer">
      <span class="todo-count"
        ><strong>{{ count }}</strong> item left</span
      >
      <Filters />
      <button @click="increment" class="clear-completed">Clear completed</button>
    </footer>
  </section>
  <footer class="info">
    <p>Double-click to edit a todo</p>
  </footer>
</template>
