// frontend-vue/src/components/TodoList.vue
<script setup lang="ts">
import type { Todo as TodoType } from '../schema';
import Todo from './Todo.vue';

interface Props {
  todos: TodoType[];
}

defineProps<Props>();
</script>

<template>
  <ul class="todo-list">
    <Todo v-for="todo in todos" :key="todo.id" :todo="todo" />
  </ul>
</template>

// frontend-react/src/components/TodoList.tsx
import { Fragment } from 'react';
import { Todo as TodoType } from '../../schema';
import { Todo } from './Todo';

interface TodoListProps {
  todos: TodoType[];
}

export const TodoList = ({ todos }: TodoListProps) => {
  return (
    <ul className="todo-list">
      {todos.map((todo) => (
        <Todo key={todo.id} todo={todo} />
      ))}
    </ul>
  );
};
