// frontend-vue/src/components/Todo.vue
<script setup lang="ts">
import type { Todo } from '../schema';

interface Props {
  todo: Todo;
}

const props = defineProps<Props>();
</script>

<template>
  <li>
    <div class="view">
      <input class="toggle" type="checkbox" />
      <label>{{ props.todo.title }}</label>
      <button class="destroy"></button>
    </div>
    <input class="edit" value="Rule the web" />
  </li>
</template>

// frontend-react/src/components/Todo.tsx
import cx from 'classnames';

import { Todo as TodoType } from '../../schema';

interface TodoProps {
  todo: TodoType;
}

export const Todo = ({ todo }: TodoProps) => {
  const editing = false;
  return (
    <li className={cx(todo.completed && 'completed', editing && 'editing')}>
      <div className="view">
        <input className="toggle" type="checkbox" />
        <label>{todo.title}</label>
        <button className="destroy"></button>
      </div>
      <input className="edit" value={todo.title} onChange={() => {}} />
    </li>
  );
};
